version: "3.7"

services:
  vscode:
    build: .
    volumes:
      - ../:/go/src/github.com/nolte/hugo-theme-bootstrap4-blog:cached
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.ssh:/root/.ssh:ro
    environment:
      - TZ=Europe/Berlin # $(cat /etc/timezone)
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"
    network_mode: "host"
